# start with: 
# docker-compose up
version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://db/schoolrecords'
      SPRING_DATASOURCE_USERNAME: schoolrecords
      SPRING_DATASOURCE_PASSWORD: schoolrecords

  db:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_DATABASE: schoolrecords
      MARIADB_USER: schoolrecords
      MARIADB_PASSWORD: schoolrecords
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
