version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://db/airplanes'
      SPRING_DATASOURCE_USERNAME: airplanes
      SPRING_DATASOURCE_PASSWORD: airplanes

  db:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_DATABASE: airplanes
      MARIADB_USER: airplanes
      MARIADB_PASSWORD: airplanes
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
