
### Create
POST http://localhost:8080/api/multiples
Content-Type: application/json

{
  "name": "Uno"
}

### Create
POST http://localhost:8080/api/multiples
Content-Type: application/json

{
  "name": "Dos"
}

### Get Many
GET http://localhost:8080/api/multiples

### Get One
GET http://localhost:8080/api/multiples/2

### Update
PUT http://localhost:8080/api/multiples/2
content-type: application/json

{
  "name": "Ketto"
}

### Connect
PUT http://localhost:8080/api/multiples/2/singles/1


### Delete
DELETE http://localhost:8080/api/multiples/2
