
### Create
POST http://localhost:8080/api/multiples
Content-Type: application/json

{
  "name": "Uno",
  "whenHappened": "2023-05-01"
}

### Create
POST http://localhost:8080/api/multiples
Content-Type: application/json

{
  "name": "Dos",
  "whenHappened": "2023-05-02"
}

### Get Many
GET http://localhost:8080/api/multiples

### Get One
GET http://localhost:8080/api/multiples/2

### Update
PUT http://localhost:8080/api/multiples/2
content-type: application/json

{
  "name": "Ketto",
  "whenHappened": "2023-05-02"
}

### Connect
PUT http://localhost:8080/api/multiples/1/singles/2


### Delete
DELETE http://localhost:8080/api/multiples/2
