
### Create
POST http://localhost:8080/api/singles
Content-Type: application/json

{
  "name": "One",
  "enumType": "ONE"
}

### Create
POST http://localhost:8080/api/singles
Content-Type: application/json

{
  "name": "Two",
  "enumType": "TWO"
}

### Get All
GET http://localhost:8080/api/singles

### Get One
GET http://localhost:8080/api/singles/2

### Update
PUT http://localhost:8080/api/singles/2
content-type: application/json

{
  "name": "Ketto",
  "enumType": "TWO"
}

### Delete
DELETE http://localhost:8080/api/singles/2
